export const types = {
    BEGIN_REQUEST: 'BEGIN_REQUEST',
    REQUEST_ERROR: 'REQUEST_ERROR',
    REQUEST_COMPLETE: 'REQUEST_COMPLETE',
    GET_ALL_USERS: 'GET_ALL_USERS',
    DELETE_USER: 'DELETE_USER'
};
